#server:
#  port: 7101
#
#spring:
#  application:
#    name: microservice-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/syq1874/springcloud_config.git
#          default-label: main        # 一定要配置，因为github升级后，已经没有 master 分支了， 而config server 默认是 master,  现在已经是 main

server:
  port: 7102

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/syq1874/springcloud_config.git
          default-label: main        # 一定要配置，因为github升级后，已经没有 master 分支了， 而config server 默认是 master,  现在已经是 main

eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    prefer-ip-address: true
    instance-id: microservice-config2